### ISSUE TITLE
Valmistada kassettide renderdamiseks vajalik info ette optimaalsemalt

### ISSUE THREAD

**Issue by mitselek** [poff-bnff/web#514]
Põhiline aeg lehe ehitamisel kulub kassettide renderdamisele.
Samuti kasutab see märkimisväärselt mälu.
Tuleb need data.lang.yaml failid teha minimaalsed ja võimalikult vähese sügavusega - täpselt layoutil vajaliku info kujuga.

**Comment by mitselek** [comment]
midagi sedalaadi andmefailid.
vajalikke andmevälju tuleb veel juurde vaadata layoutide pealt
```
cassetteCarouselPicsFilms:
  - /assets/img/static/placeholder_hd_1.jpg
titleBox:
  title: ''
  original: ''
  en: ''
  et: ''
  ru: ''
year: ''
premierTypes: []
countryNames: []
credentials:
  directorofphotography: []
  editor: []
  productioncompany: []
  director: []
  producer: []
  screenwriter: []
  cast: []
synopsisBox:
  festivalEditionNames: []
  programmeNames: []
  genres: []
  keywords: []
  synopsis_md: ''
runtime: ''
languages: []
directors:
  -
    portrait: ''
    name: ''
    biography: ''
    filmography: ''
presenters:
  - 
    text: ''
    organisations:
      - 
        ...
```
